- name: Playbook for Web Services initialization
  gather_facts: true
  hosts: web-backend
  serial: 10
  remote_user: root

  tasks:
    - name: Install the OS packages
      ansible.builtin.apt:
        name:
          - python-setuptools
          - nginx
          - git
          - python3
          - python3-pip
        state: present
        update_cache: yes