- name: Play1
  gather_facts: true
  hosts: web-1
  serial: 10
  remote_user: root

  tasks:
    - name: Simple ping
      ansible.builtin.ping:

    - name: Simple shell
      ansible.builtin.shell: date